### ISSUE TITLE
Issue with Tsinghua Twitter Depression Dataset

### ISSUE THREAD

**Issue by mukurgupta** [kharrigian/mental-health-datasets#4]
Hello,

Thanks a lot for this repo. This is a huge help in my current study.
I'm facing issues with the link of one of the Datasets. I can't seem to find Tsinghua Twitter Depression Dataset on the link you provided (http://depressiondetection.droppages.com)

Could you please help me with this?
Thanks

**Comment by kharrigian** [comment]
Thank you for the notice. The dataset you are looking for has several issues that render it ill-suited for distribution. We contacted the authors about these issues last year, but never received a reply. It is possible that the dataset in question has been made unavailable based on our recommendations, or it is possible that the domain used to host the dataset has expired. The latter is more likely, as I have noticed issues with droppages links used to host other datasets from the research group.

We will be removing the link to the dataset in an upcoming update. If you would still like to access the dataset, we recommend contacting the original authors directly.
