### ISSUE TITLE
Most of the datasets effectively not exist

### ISSUE THREAD

**Issue by Serbernari** [kharrigian/mental-health-datasets#5]
There is no download links in the papers or in the google for almost all of the datasets listed, and authors of the papers do not respond on the mail requests. I suggest adding column with download links to help others researchers save time.

**Comment by kharrigian** [comment]
Hi,

You can find links (where available) in `data_sources.xlsx`. In general, we expect most datasets not to be available via a hyperlink. Instead, we expect most datasets to be safeguarded behind data usage agreements from their respective authors. We unfortunately have no control over whether authors of the respective datasets choose to respond to email requests.

**Comment by Serbernari** [comment]
Oh, ok, I see! Thank you for your response and awesome repo!
